### ISSUE TITLE
1.0.0-Alpha

### ISSUE THREAD

**Issue by helpmeagain** [felipecomarques/blackwell#30]
# 1.0.0-Alpha
## Features
- [x] Password Recovery
- [x] PDF Generation
- [x] Create Specific Medical Records (#34)
- [X] Fetch Patients with Pagination (f14c389)
- [x] Fetch Clinician with Pagination (c3e64d2)
- [x] ~Fetch Specific Medical Records with Pagination~
- [ ] Possibility of deletion medicals records after 20 years
- [x] Add Redis
- [x] ~Add Attachment Usage~
- [x] Create Continuous Development
- [x] Create Index Route (768ba16)
- [x] Add Database Seed (1490500)

## Adjustments
- [x] ~Patient Data (#35)~
- [x] ~Clinician Data (#36)~
- [x] Universal Medical Record Data (#37)
- [x] Differentiate General Medical Record from Specific (#34)
- [x] Separate Medical Record Logic from Patient (a518047)
- [x] Remove Consultations (5931cc0)
- [X] Update `@faker-js/faker` to use PT-BR (c8828ef)
- [x] Update README and Project Description

## Database
- [x] ~Perform Correct Joins~
- [x] Model Database with New Information
- [x] ~Resolve PK and FK Implementation~
- [x] Create Gender Enum (0aac927)

## Authorization
- [x] Use `@CurrentUser` to Verify User Request Permission (180b4ac)
- [x] Use Roles via Payload
- [x] Create General Medical Record Authorization (#33)
- [x] Create Specific Medical Record Authorization (#33)

## Validation
- [ ] Character Limit for All Fields
- [ ] Valid Phone Number
- [x] Valid Password for Patients and Clinicians (a426b56)

## Bugs
- [ ] Fix 500 Error when Foreign Key Fails
- [x] Correct Gender Implementation in Prisma Mapper (0aac927)
- [ ] Fix Empty Field in Fetch Clinicians or Patients When a Field is Incorrect
